import { test, expect } from '@playwright/test';

test.describe('Multi-Chrome Parallel Workflow: Live Attack & Surveillance', () => {
  test.beforeEach(async ({ request }) => {
    await request.post('/api/clear-buffer');
    await request.post('/api/soar/unblock');
  });

  test('Two concurrent tabs: Action Worker on / vs Inspector on /security-dashboard', async ({ browser }) => {
    // 1. Initialize Multi-Tab Session in single browser context
    const context = await browser.newContext({ baseURL: 'http://localhost:3000' });
    const tab1 = await context.newPage(); // Action Worker
    const tab2 = await context.newPage(); // Inspector / Surveillance Worker

    // 2. Open endpoints simultaneously
    await Promise.all([
      tab1.goto('/signup'),
      tab2.goto('/security-dashboard'),
    ]);

    // 3. Tab 1 generates authentication actions (1 signup + failed attempts)
    await tab1.fill('#reg-user', 'Utkarsh_MultiTab');
    await tab1.fill('#reg-pass', 'SecurePass#2026');
    await tab1.fill('#reg-hint', 'DogName');
    tab1.once('dialog', (d) => d.accept());
    await tab1.click('button:has-text("Sign Up")');

    // Tab 1 simulates failed guesses
    for (const guess of ["' OR '1'='1", 'admin123', '<script>alert(1)</script>']) {
      await tab1.fill('#login-user', 'Utkarsh_MultiTab');
      await tab1.fill('#login-pass', guess);
      await tab1.click('button:has-text("Log In")');
      await expect(tab1.locator('#hint-msg')).toContainText('DogName');
    }

    // 4. Tab 2 observes live audit rows generated by Tab 1 without reload
    const targetRow = tab2.locator('#log-table tbody tr', { hasText: 'Utkarsh_MultiTab' }).first();
    await expect(targetRow).toBeVisible({ timeout: 5000 });

    // 5. Trigger burst in Tab 1
    await tab1.request.post('/api/simulate-burst', { data: { n: 200, target: 'Utkarsh_MultiTab' } });

    // 6. Tab 2 triggers Dual-Engine Comparison (Jev AI vs Laya)
    await tab2.click('button:has-text("Compare Jev vs Laya")');
    await expect(tab2.locator('#eval-desc-jev')).toContainText(/brute|stuffing|sqli|xss|attack/i, { timeout: 20000 });
    await expect(tab2.locator('#eval-desc-laya')).toContainText(/brute|stuffing|sqli|xss|attack/i);

    // Verify confidence & latencies
    for (const id of ['#eval-conf-jev', '#eval-conf-laya']) {
      const conf = parseFloat((await tab2.locator(id).innerText()).replace(/[^0-9.]/g, ''));
      expect(conf).toBeGreaterThan(80);
    }
    for (const id of ['#eval-lat-jev', '#eval-lat-laya']) {
      await expect(tab2.locator(id)).toContainText(/ms/);
    }

    await context.close();
  });
});
